apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-service
spec:
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
  replicas: 2
  selector:
    matchLabels:
      app: vote-service
  template:
    metadata:
      labels:
        app: vote-service
    spec:
      serviceAccountName: mopl-service
      containers:
      - name: vote-service
        readinessProbe:
          httpGet:
            path: /vote/common/health/ping
            port: 3000
          initialDelaySeconds: 5
          timeoutSeconds: 3
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /vote/common/health/ping
            port: 3000
          initialDelaySeconds: 5
          timeoutSeconds: 3
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 3
        image: 852637827699.dkr.ecr.ap-northeast-2.amazonaws.com/mopl/vote-service:latest
        ports:
        - containerPort: 3000
        - containerPort: 3001
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: mopl-db-url
              key: vote_database_url
        - name: ADMIN_HTTP_PORT
          value: "3000"
        - name: USER_HTTP_PORT
          value: "3001"
        - name: ADMIN_BASE_PATH
          value: /vote
        - name: USER_BASE_PATH
          value: /vote
        - name: S3_BUCKET_NAME
          value: mopl-vote-p-an2
        - name: ADMIN_GLOBAL_PREFIX
          value: vote
        - name: USER_GLOBAL_PREFIX
          value: vote
        - name: APARTMENT_SERVICE_URL
          value: http://apartment-service:3002
        - name: AUDIT_SERVICE_URL
          value: http://audit-service:3002
        - name: REDIS_URI
          value: redis://redis.uaod2h.0001.apn2.cache.amazonaws.com:6379/3
        - name: MOPL_URL
          value: https://admin.mopl.app

        volumeMounts:
        - name: backend-keys
          mountPath: /usr/src/app/public.admin.key
          subPath: public.admin.key
        - name: backend-keys
          mountPath: /usr/src/app/public.user.key
          subPath: public.user.key

      volumes:
      - name: backend-keys
        secret:
          secretName: backend-keys
