apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
images:
  - name: 852637827699.dkr.ecr.ap-northeast-2.amazonaws.com/mopl/user-service
    newTag: prod-20230630081537-R1

patches:
  #  - target:
  #      kind: Deployment
  #    path: set_memory.yaml
  - target:
      kind: Deployment
    path: set_env.yaml
