apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

images:
  - name: 852637827699.dkr.ecr.ap-northeast-2.amazonaws.com/mopl/verification-service
    newName: 796457042442.dkr.ecr.ap-northeast-2.amazonaws.com/mopl-dev/verification-service
    newTag: dev-20230607081618

namePrefix: dev-
namespace: smartparking-dev

replicas:
  #fixme
  - name: verification-service
    count: 1

configMapGenerator:
  - name: nginx-config
    #namespace: smartparking
    behavior: create
    files:
      - ./server_block.conf

patches:
  - target:
      kind: Ingress
      #fixme
      name: verification-service-ingress
    path: ing_patch.yaml
  #  - target:
  #      kind: Deployment
  #    path: set_memory.yaml
  - target:
      kind: Deployment
    path: set_env.yaml
  - target:
      kind: Ingress
    path: set_ing_annotations.yaml