apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-service
spec:
  template:
    spec:
      containers:
        - name: vote-service
          env:
            #fixme
            - name: S3_BUCKET_NAME
              value: mopl-vote-d-an2
            - name: APARTMENT_SERVICE_URL
              value: http://dev-apartment-service:3002
            - name: AUDIT_SERVICE_URL
              value: http://dev-audit-service:3002
            - name: REDIS_URI
              value: redis://redis.odqsrp.0001.apn2.cache.amazonaws.com:6379/3
            - name: ARGOCD-NOTI-TEST
              value: ARGOCD-NOTI-TEST11
            - name: SWAGGER_USER_ID
              value: dev_id
            - name: SWAGGER_USER_PASSWORD
              value: dev_password
            - name: NODE_ENV
              value: develop
            - name: TEST
              value: TEST10
            - name: MOPL_URL
              value: https://admin.mopl-dev.com