apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation-service
spec:
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
  replicas: 2
  selector:
    matchLabels:
      app: reservation-service
  template:
    metadata:
      labels:
        app: reservation-service
    spec:
      serviceAccountName: mopl-service
      containers:
      - name: reservation-service
        readinessProbe:
          httpGet:
            path: /reservation/common/health/ping
            port: 3000
          initialDelaySeconds: 10
          timeoutSeconds: 3
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /reservation/common/health/ping
            port: 3000
          initialDelaySeconds: 10
          timeoutSeconds: 3
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 5
        image: 852637827699.dkr.ecr.ap-northeast-2.amazonaws.com/mopl/reservation-service:latest
        ports:
        - containerPort: 3000
        - containerPort: 3001
        - containerPort: 3002
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: mopl-db-url
              key: reservation_database_url
        - name: ADMIN_HTTP_PORT
          value: "3000"
        - name: USER_HTTP_PORT
          value: "3001"
        - name: INTERNAL_HTTP_PORT
          value: "3002"
        - name: ADMIN_BASE_PATH
          value: /reservation
        - name: USER_BASE_PATH
          value: /reservation
        - name: ADMIN_GLOBAL_PREFIX
          value: reservation
        - name: USER_GLOBAL_PREFIX
          value: reservation
        - name: S3_BUCKET_NAME
          value: mopl-reservation-p-an2
        - name: AUDIT_SERVICE_URL
          value: 'http://audit-service:3002'
        - name: APARTMENT_SERVICE_URL
          value: 'http://apartment-service:3002'

        volumeMounts:
        - name: backend-keys
          mountPath: /usr/src/app/public.user.key
          subPath: public.user.key
        - name: backend-keys
          mountPath: /usr/src/app/public.admin.key
          subPath: public.admin.key

      volumes:
      - name: backend-keys
        secret:
          secretName: backend-keys
