apiVersion: apps/v1
kind: Deployment
metadata:
  name: forum-service
spec:
  template:
    spec:
      containers:
        - name: forum-service
          env:
            #fixme
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: mopl-db-pt-url
                  key: forum_database_url
            - name: S3_BUCKET_FOR_FILE_UPLOAD
              value: mopl-forum-q-an2
            - name: APARTMENT_SERVICE_URL
              value: http://pt-apartment-service:3002
            - name: AUDIT_SERVICE_URL
              value: http://pt-audit-service:3002
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: service
                    operator: In
                    values:
                      - mopl-qa
      tolerations:
        - effect: "NoSchedule"
          key: "service"
          operator: "Equal"
          value: "mopl-qa"