apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-frontend
spec:
  template:
    spec:
      containers:
        - name: admin-frontend
          env:
            #fixme
            - name: API_BASE_URL
              value: https://admin-api.mopl-dev.com
            - name: SESSION_SECRET
              value: moplproductionsecret
            - name: PORT
              value: "3000"
            - name: API_USER_URL
              value: https://user-api.mopl-dev.com
