apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: 852637827699.dkr.ecr.ap-northeast-2.amazonaws.com/mopl/admin-frontend
    newTag: prod-20230629132449-R13

patches:
  #  - target:
  #      kind: Deployment
  #    path: set_memory.yaml
  - target:
      kind: Deployment
    path: set_env.yaml
