apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  template:
    spec:
      containers:
        - name: user-service
          env:
            #fixme
            - name: REDIS_URI
              value: redis://redis.odqsrp.0001.apn2.cache.amazonaws.com:6379/1
            - name: S3_BUCKET_NAME
              value: mopl-user-d-an2
            - name: APARTMENT_SERVICE_URL
              value: http://dev-apartment-service:3002
            - name: AUTHN_SERVICE_URL
              value: http://dev-authn-service:3002
            - name: SWAGGER_USER_ID
              value: dev_id
            - name: SWAGGER_USER_PASSWORD
              value: dev_password
            - name: NODE_ENV
              value: develop
            - name: JWT_EXPIRES_IN_VOTER
              value: 1d