apiVersion: apps/v1
kind: Deployment
metadata:
  name: device-service
spec:
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
  replicas: 2
  selector:
    matchLabels:
      app: device-service
  template:
    metadata:
      labels:
        app: device-service
    spec:
      serviceAccountName: mopl-service
      containers:
      - name: device-service
        readinessProbe:
          httpGet:
            path: /device/common/health/ping
            port: 3000
          initialDelaySeconds: 10
          timeoutSeconds: 3
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /device/common/health/ping
            port: 3000
          initialDelaySeconds: 10
          timeoutSeconds: 3
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 5
        image: 852637827699.dkr.ecr.ap-northeast-2.amazonaws.com/mopl/device-service:latest
        ports:
        - containerPort: 3000
        - containerPort: 3001
        - containerPort: 3002
        - containerPort: 3003
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mopl-db-url
              key: device_mongo_url
        - name: REDIS_URI
          value: redis://redis.uaod2h.0001.apn2.cache.amazonaws.com:6379/2
        - name: ADMIN_HTTP_PORT
          value: "3000"
        - name: USER_HTTP_PORT
          value: "3001"
        - name: INTERNAL_HTTP_PORT
          value: "3002"
        - name: DEVICE_HTTP_PORT
          value: "3003"
        - name: JWT_EXPIRES_IN
          value: 3d
        - name: S3_BUCKET_NAME
          value: mopl-device-p-an2
        - name: ADMIN_GLOBAL_PREFIX
          value: device
        - name: USER_GLOBAL_PREFIX
          value: device
        - name: DEVICE_GLOBAL_PREFIX
          value: device
        - name: APARTMENT_SERVICE_URL
          value: http://apartment-service:3002
        - name: AUDIT_SERVICE_URL
          value: http://audit-service:3002
        - name: ENCRYPT_KEY
          value: siliconbridgeinc 
        volumeMounts:
        - name: backend-keys
          mountPath: /usr/src/app/private.device.key
          subPath: private.device.key
        - name: backend-keys
          mountPath: /usr/src/app/public.device.key
          subPath: public.device.key
        - name: backend-keys
          mountPath: /usr/src/app/public.user.key
          subPath: public.user.key
        - name: backend-keys
          mountPath: /usr/src/app/public.admin.key
          subPath: public.admin.key

      volumes:
      - name: backend-keys
        secret:
          secretName: backend-keys
