apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  #fixme
  - name: 852637827699.dkr.ecr.ap-northeast-2.amazonaws.com/mopl/reservation-service
    newTag: qa-20230621030422

namePrefix: qa-
namespace: smartparking-qa

replicas:
  #fixme
  - name: reservation-service
    count: 1

patches:
  - target:
      kind: Ingress
      #fixme
      name: reservation-service-ingress
    path: ing_patch.yaml
  #  - target:
  #      kind: Deployment
  #    path: set_memory.yaml
  - target:
      kind: Deployment
    path: set_env.yaml
  - target:
      kind: Ingress
    path: set_ing_annotations.yaml