apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation-service
spec:
  template:
    spec:
      containers:
        - name: reservation-service
          env:
            #fixme
            - name: S3_BUCKET_NAME
              value: mopl-reservation-q-an2
            - name: APARTMENT_SERVICE_URL
              value: 'http://qa-apartment-service:3002'
            - name: AUDIT_SERVICE_URL
              value: 'http://qa-audit-service:3002'
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: service
                    operator: In
                    values:
                      - mopl-qa
      tolerations:
        - effect: "NoSchedule"
          key: "service"
          operator: "Equal"
          value: "mopl-qa"