apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: team-backendsolutiondev-mopl-alert
    notifications.argoproj.io/subscribe.on-sync-failed.slack: team-backendsolutiondev-mopl-alert
    notifications.argoproj.io/subscribe.on-sync-running.slack: team-backendsolutiondev-mopl-alert
    notifications.argoproj.io/subscribe.on-sync-status-unknown.slack: team-backendsolutiondev-mopl-alert
    notifications.argoproj.io/subscribe.on-health-degraded.slack: team-backendsolutiondev-mopl-alert
    #notifications.argoproj.io/subscribe.on-deployed.slack: team-backendsolutiondev-mopl-alert
  name: authn-service-dev
  namespace: argocd
spec:
  destination:
    namespace: smartparking-dev
    server: https://A0E2A5B6B6AFC4491CB4E172A391E2AA.sk1.ap-northeast-2.eks.amazonaws.com
  project: smartparking-dev
  source:
    path: authn-service/env/dev/
    repoURL: https://github.com/backend-sw-development-team4/smartparking-gitops.git
    targetRevision: main
  syncPolicy:
    automated: {}