apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

images:
  - name: 852637827699.dkr.ecr.ap-northeast-2.amazonaws.com/mopl/audit-service
    newName: 796457042442.dkr.ecr.ap-northeast-2.amazonaws.com/mopl-dev/audit-service
    newTag: dev-20230626060445

namePrefix: dev-
namespace: smartparking-dev

replicas:
  #fixme
  - name: audit-service
    count: 1

patches:
  - target:
      kind: Ingress
      #fixme
      name: audit-service-ingress
    path: ing_patch.yaml
  #  - target:
  #      kind: Deployment
  #    path: set_memory.yaml
  - target:
      kind: Deployment
    path: set_env.yaml
  - target:
      kind: Ingress
    path: set_ing_annotations.yaml